In [54]:
# !pip install nltk openai pandas python-dotenv
!pip install -U plotly nbformat kaleido

Requirement already satisfied: plotly in ./.venv/lib/python3.11/site-packages (6.7.0)
Requirement already satisfied: nbformat in ./.venv/lib/python3.11/site-packages (5.10.4)
Collecting kaleido
  Downloading kaleido-1.2.0-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: narwhals>=1.15.1 in ./.venv/lib/python3.11/site-packages (from plotly) (2.19.0)
Requirement already satisfied: packaging in ./.venv/lib/python3.11/site-packages (from plotly) (26.0)
Requirement already satisfied: fastjsonschema>=2.15 in ./.venv/lib/python3.11/site-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in ./.venv/lib/python3.11/site-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in ./.venv/lib/python3.11/site-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in ./.venv/lib/python3.11/site-packages (from nbformat) (5.14.3)
Collecting choreographer>=1.1.1 (from kaleido)
  Downloading choreographer-1.2.1-py3-none-any.whl.metadata (6.8 kB)
Collecting logistro>=1.0.8 (from kaleido)
  Downloading logistro-2.0.1-py3-none-any.whl.metadata (3.9 kB)
Collecting orjson>=3.10.15 (from kaleido)
  Downloading orjson-3.11.8-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (41 kB)
Collecting pytest-timeout>=2.4.0 (from kaleido)
  Downloading pytest_timeout-2.4.0-py3-none-any.whl.metadata (20 kB)
Collecting simplejson>=3.19.3 (from choreographer>=1.1.1->kaleido)
  Downloading simplejson-3.20.2-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.2 kB)
Requirement already satisfied: attrs>=22.2.0 in ./.venv/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in ./.venv/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in ./.venv/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in ./.venv/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in ./.venv/lib/python3.11/site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.9.4)
Collecting pytest>=7.0.0 (from pytest-timeout>=2.4.0->kaleido)
  Downloading pytest-9.0.3-py3-none-any.whl.metadata (7.6 kB)
Collecting iniconfig>=1.0.1 (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido)
  Downloading iniconfig-2.3.0-py3-none-any.whl.metadata (2.5 kB)
Collecting pluggy<2,>=1.5 (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido)
  Downloading pluggy-1.6.0-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: pygments>=2.7.2 in ./.venv/lib/python3.11/site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (2.20.0)
Requirement already satisfied: typing-extensions>=4.4.0 in ./.venv/lib/python3.11/site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat) (4.15.0)
Downloading kaleido-1.2.0-py3-none-any.whl (68 kB)
Downloading choreographer-1.2.1-py3-none-any.whl (49 kB)
Downloading logistro-2.0.1-py3-none-any.whl (8.6 kB)
Downloading orjson-3.11.8-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (133 kB)
Downloading pytest_timeout-2.4.0-py3-none-any.whl (14 kB)
Downloading pytest-9.0.3-py3-none-any.whl (375 kB)
Downloading pluggy-1.6.0-py3-none-any.whl (20 kB)
Downloading iniconfig-2.3.0-py3-none-any.whl (7.5 kB)
Downloading simplejson-3.20.2-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (144 kB)
Installing collected packages: simplejson, pluggy, orjson, logistro, iniconfig, pytest, choreographer, pytest-timeout, kaleido
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9/9 [kaleido]m8/9 [kaleido]apher]
Successfully installed choreographer-1.2.1 iniconfig-2.3.0 kaleido-1.2.0 logistro-2.0.1 orjson-3.11.8 pluggy-1.6.0 pytest-9.0.3 pytest-timeout-2.4.0 simplejson-3.20.2

In [1]:
# ============================================================
# 0) Imports + OpenRouter client setup
# ============================================================
import os, json, re
from pathlib import Path
from dotenv import load_dotenv 
import pandas as pd
from nltk.metrics.scores import precision, recall, f_measure
from openai import OpenAI

load_dotenv()
# open router key
# os.environ["OPENROUTER_API_KEY"] = "set your key"

client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=os.getenv("OPENROUTER_API_KEY"),
)

MODELS_TO_TEST = [
    "anthropic/claude-opus-4.6",
    "google/gemini-3.1-pro-preview",
    "google/gemini-2.5-pro",
    "openai/gpt-5.4",
    "moonshotai/kimi-k2.5"
]

In [ ]:
# ============================================================
# 1) Paths
# ============================================================
SYSTEM_PROMPT_PATH = Path("system_prompt_cot_updated.txt")
GROUND_TRUTH_PATH  = Path("ground_truth_irac.json")

Q_SUPERSET_CSV = {
    "Q1": Path("Questions_superset_rows - Q1.csv"),
    "Q2": Path("Questions_superset_rows - Q2.csv"),
    "Q3": Path("Questions_superset_rows - Q3.csv"),
    "Q4": Path("Questions_superset_rows - Q4.csv"),
    "Q5": Path("Questions_superset_rows - Q5.csv")
}

OUTDIR = Path("irac_outputs/updated_cot")
OUTDIR.mkdir(parents=True, exist_ok=True)

In [3]:
# ============================================================
# 2) Load system prompt + ground truth JSON
# ============================================================
SYSTEM_PROMPT = SYSTEM_PROMPT_PATH.read_text(encoding="utf-8").strip()
GROUND_TRUTH = json.loads(GROUND_TRUTH_PATH.read_text(encoding="utf-8"))

In [4]:
# ============================================================
# 3) Load superset rows CSVs (NOW including Hohfeldian columns)
#    Required columns:
#      - Row_ID
#      - treatytext
#      - actorholder
#      - action
#      - actoraffected
# ============================================================
def load_superset_rows(csv_path: Path) -> pd.DataFrame:
    df = pd.read_csv(csv_path)

    required = ["Row_ID", "treatytext", "actorholder", "action", "actoraffected"]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"{csv_path.name} missing columns: {missing}")

    return df[required].copy()

SUPERSETS = {q: load_superset_rows(path) for q, path in Q_SUPERSET_CSV.items()}

In [ ]:
# ============================================================
# 4) Fact patterns + C1/C2 text (fill these; later load from file)
# ============================================================
QUESTIONS = {
    "Q1": {
        "fact_pattern": "An Australian biotechnology company conducts a private expedition to collect marine genetic resources (MGRs) in areas beyond national jurisdiction (ABNJ). The collected materials are sequenced in-house, and the resulting digital sequence information (DSI) is published in open-access repositories. The same company later relies on this DSI to develop a commercially valuable enzyme. No prior informed consent (PIC) or mutually agreed terms (MAT) were established, and no monetary or non-monetary benefit-sharing has occurred. The company argues that because the material was collected in ABNJ and only DSI is being used, rather than the physical samples, no benefit-sharing obligations apply under current international law. The competent authority of Australia has not taken regulatory steps to monitor or require disclosure of the activity. This scenario raises questions about the extent to which companies and States bear substantive obligations to ensure benefit-sharing when MGRs are accessed in ABNJ and subsequently used in commercial applications through DSI, particularly in the absence of clear jurisdictional triggers, prior agreements, or internationally coordinated oversight mechanisms.",
        "C1": "Benefit-sharing obligations apply to the commercial utilisation of DSI derived from ABNJ MGRs in this scenario, and Australia must ensure fair and equitable benefit-sharing (including non-monetary and, where applicable, monetary benefits).",
        "C2": "No benefit-sharing obligations apply to the commercial utilisation of DSI derived from ABNJ MGRs in this scenario, so Australia has no duty (on these facts) to ensure benefit-sharing from the company’s use of the published DSI.",
    },
    "Q2": {
        "fact_pattern": "A university-affiliated researcher from Brazil applies for access to marine genetic resources (MGRs) located within the exclusive economic zone (EEZ) of Argentina. Both Brazil and Argentina are Parties to the Convention on Biological Diversity (CBD) and the Nagoya Protocol. The target species are found in an area inhabited by an Indigenous community with longstanding custodianship of the surrounding marine environment and traditional knowledge (TK) associated with the biological properties of the organisms. Argentina’s national competent authority grants the researcher an access permit for academic sample collection. The researcher does not engage with the Indigenous community, and neither the permitting process nor any domestic procedure includes consultation or prior informed consent (PIC) from the TK holders. No mutually agreed terms (MAT) are established, and no plans are made for benefit-sharing with the community. The samples are collected and exported to Brazil for analysis without further engagement. This fact pattern raises questions about the legal adequacy of State-issued permits that omit community-level consent when TK is clearly associated with marine genetic resources within the granting State’s jurisdiction.",
        "C1": "Access to MGRs and associated TK located within national jurisdiction requires engagement with Indigenous Peoples and Local Communities (IPLCs), including PIC/approval and involvement and the establishment of MAT, where TK is associated with the genetic resources and where IPLCs have recognised rights.",
        "C2": "Access to MGRs and associated TK within national jurisdiction does not require engagement with IPLCs in this scenario, because State authority over genetic resources is sufficient and IPLC PIC/approval is not legally required unless specifically mandated under domestic law.",
    },
    "Q3": {
        "fact_pattern": "A publicly funded research institution based in Peru initiates a project involving the development of bioactive compounds derived from marine genetic resources (MGRs) located within Brazil’s national jurisdiction. The Peruvian researchers rely on traditional knowledge (TK) obtained from an Indigenous community in Brazil, whose members provided ethnobiological information that guided the selection of marine species and the methodology for compound extraction. The project is formally classified as non-commercial research, and access is authorised by Brazil’s national competent authority under that designation. Accordingly, mutually agreed terms (MAT) are limited to standard reporting obligations, and no benefit-sharing mechanisms are triggered at the point of access. Several years later, the compounds developed under the project attracted substantial interest from a Peruvian pharmaceutical company, which began developing and patenting commercial products based on the initial research. Since the project was never required to track downstream uses or disclose transitions from non-commercial to commercial applications, the Indigenous community receives no benefits and remains unaware of the commercialisation pathway. This case raises questions concerning the legal effect of access agreements that limit benefit-sharing responsibilities to the initial user, particularly where TK contributed to early-stage research that enabled later commercialisation",
        "C1": "Benefit-sharing obligations under the Nagoya Protocol extend to downstream commercial uses of genetic resources and associated TK, even when initial access was classified as non-commercial. MAT and domestic ABS systems must address changes of intent, third-party use and commercialisation. Provider and user countries retain ongoing duties to ensure fair and equitable sharing of benefits.",
        "C2": "Benefit-sharing obligations do not extend automatically to downstream commercial uses when initial access was authorised as non-commercial. If MAT did not include clauses on commercialisation, third-party use or changes of intent, and if domestic legislation does not impose such obligations, later benefit-sharing duties may not arise for subsequent users."
    },
    "Q4": {
        "fact_pattern": "A multinational research consortium involving institutions from Portugal, Cape Verde and Brazil undertakes a marine sampling expedition to collect genetic resources from two zones: (1) within India’s exclusive economic zone (EEZ), and (2) an adjacent area beyond national jurisdiction (ABNJ). No access agreements are concluded with Indian authorities. The sampling design and species selection rely on traditional knowledge (TK) informally provided by an Indigenous community in India. The expedition yields extensive digital sequence information (DSI), later deposited in open-access repositories. A Belgian biotechnology company, unaffiliated with the consortium, accesses the open DSI and synthesises a compound that becomes the active ingredient in a successful commercial cosmetic product. The product’s commercial viability depends on three inputs: Genetic traits from samples collected inside India’s EEZ, Genetic traits from ABNJ samples, and TK from the Indigenous community, which guided species identification. No PIC was obtained from the community. No benefit-sharing was arranged with India or with IPLCs. Neither the consortium nor Belgium has mechanisms requiring tracking of downstream use, change of intent, or transitions from non-commercial to commercial utilisation. This raises complex questions across overlapping regimes (CBD, Nagoya, BBNJ) regarding: attribution of benefit-sharing duties where resources cross jurisdictional regimes, the legal effect of missing PIC/TK arrangements, obligations arising on the commercialisation of DSI that originates partly in ABNJ, user-country obligations (Belgium), provider-country obligations (India), and obligations of the consortium States.",
        "C1": "Benefit-sharing obligations arise under the CBD, the Nagoya Protocol and the BBNJ Agreement for downstream commercial utilisation of MGRs and associated TK collected across EEZ and ABNJ boundaries. These obligations apply regardless of the open publication of DSI and regardless of the absence of initial PIC arrangements. Provider-country rights, IPLC rights, and ABNJ benefit-sharing obligations all remain engaged.",
        "C2": "Benefit-sharing obligations do not arise for the downstream commercial use of DSI in this scenario. The open publication of DSI, the lack of formal access agreements, and the absence of enforceable PIC requirements limit or extinguish obligations under Nagoya and CBD, while BBNJ DSI-related benefit-sharing does not extend to commercial users accessing openly available DSI ex situ."
    },
    "Q5": {
        "fact_pattern": "A regional oceanographic institute based in Indonesia enters into a public-private partnership with a biotechnology start-up from South Africa to collect marine genetic resources (MGRs) of areas beyond national jurisdiction. The samples are stored in Indonesia and later transferred to South Africa for processing and sequencing. The resulting digital sequence information (DSI) is deposited in a proprietary database managed by the private Indonesian partner. A commercial product is eventually developed using the inputs. No prior informed consent (PIC) was obtained from any Indigenous Peoples and Local Communities (IPLCs), and no benefit-sharing measures were agreed upon. The Indonesian State remains unaware of the downstream commercialisation. This case presents regulatory issues in tracing resource origin, responsibilities linked to transboundary transfers, and the treatment of DSI derived from multi-jurisdictional sampling.",
        "C1": "States involved in the collection, storage, transfer and commercial utilisation of MGRs and DSI originating from ABNJ have obligations under the BBNJ Agreement to ensure transparency, traceability, timely notification to the Clearing-House, deposition of DSI in publicly accessible repositories, and the fair and equitable sharing of monetary and non-monetary benefits. These duties apply even when commercialisation occurs without initial State awareness.",
        "C2": "Only States bear legal obligations under the BBNJ Agreement. Private entities, including downstream biotechnology companies, do not have direct treaty duties. Commercialisation without PIC, MAT or DSI deposition does not itself violate the Agreement unless States fail to adopt or enforce the domestic regulatory measures required by Articles 12 and 14."
    }
}

In [6]:
# ============================================================
# 5) Prompt builder + LLM call + JSON parse
#    (NOW includes actor_holder / action / actor_affected per row)
# ============================================================
def build_user_prompt(q: str, fact_pattern: str, df_rows: pd.DataFrame, c1: str, c2: str) -> str:
    rows = "\n\n".join(
        "\n".join([
            str(r.Row_ID).strip(),
            f"actorholder: {str(r.actorholder).strip()}",
            f"action: {str(r.action).strip()}",
            f"actoraffected: {str(r.actoraffected).strip()}",
            str(r.treatytext).strip(),
        ])
        for _, r in df_rows.iterrows()
    )

    return f"""question_number: {q}

FACT PATTERN:
{fact_pattern}

TREATY ROWS (ID + Hohfeldian mapping + exact treaty text):
{rows}

CONCLUSIONS:
C1: {c1}
C2: {c2}
""".strip()

def extract_json(text: str) -> dict:
    m = re.search(r"\{.*\}", text, flags=re.DOTALL)
    if not m:
        raise ValueError("No JSON object found in model output.")
    return json.loads(m.group(0))

def call_llm(system_prompt: str, user_prompt: str, model_name: str) -> dict:
    resp = client.chat.completions.create(
        model=model_name,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        temperature=0,
    extra_body={
                "seed": 42,
                "provider": {"allow_fallbacks": False},
                "reasoning": {"enabled": True}
                # "reasoning": {"effort": "high", "exclude": True},
            },
    )
    return extract_json(resp.choices[0].message.content)

In [7]:
# ============================================================
# 6) Validation + evaluation (rules + edges)
# ============================================================
def validate_pred(pred: dict):
    assert "question_number" in pred
    for k in ["irac_C1", "irac_C2"]:
        obj = pred[k]
        for needed in ["issue", "rules_selected", "analysis", "conclusion", "edges_support"]:
            assert needed in obj

        for rr in obj["rules_selected"]:
            assert "id" in rr and "text" in rr

        for e in obj["edges_support"]:
            assert "|" in e and " " not in e, f"Edge has spaces or wrong format: {e}"

def prf(gold_set: set, pred_set: set):
    p = precision(gold_set, pred_set) or 0.0
    r = recall(gold_set, pred_set) or 0.0
    f1 = f_measure(gold_set, pred_set) or 0.0
    return p, r, f1

def eval_one(q: str, pred: dict, gt: dict, model_name: str) -> pd.DataFrame:
    rows = []
    for concl in ["C1", "C2"]:
        pred_obj = pred[f"irac_{concl}"]
        gt_obj = gt[q][concl]

        pred_rules = {x["id"].strip() for x in pred_obj["rules_selected"]}
        gold_rules = set(gt_obj["rules_selected"])

        pred_edges = {x.strip() for x in pred_obj["edges_support"]}
        gold_edges = set(gt_obj["edges_support"])

        p_r, r_r, f1_r = prf(gold_rules, pred_rules)
        p_e, r_e, f1_e = prf(gold_edges, pred_edges)

        rows += [
            {"model": model_name, "question_number": q, "conclusion": concl, "metric": "rules_selected",
             "precision": p_r, "recall": r_r, "f1": f1_r,
             "gold_size": len(gold_rules), "pred_size": len(pred_rules)},
            {"model": model_name, "question_number": q, "conclusion": concl, "metric": "edges_support",
             "precision": p_e, "recall": r_e, "f1": f1_e,
             "gold_size": len(gold_edges), "pred_size": len(pred_edges)},
        ]
    return pd.DataFrame(rows)

In [ ]:
# ============================================================
# 7) Run Q1-Q5, save prediction files + metrics.csv
# ============================================================
import time

all_metrics = []
questions_to_test = ["Q1", "Q2", "Q3", "Q4", "Q5"]
total_models = len(MODELS_TO_TEST)
total_questions = len(questions_to_test)

for m_idx, model_name in enumerate(MODELS_TO_TEST, 1):
    print(f"\n[{m_idx}/{total_models}] Testing model: {model_name}")
    print("-" * 50)
    safe_model_name = model_name.replace("/", "_")
    
    for q_idx, q in enumerate(questions_to_test, 1):
        print(f"  -> Processing {q} ({q_idx}/{total_questions})...", end=" ", flush=True)
        start_time = time.time()
        
        user_prompt = build_user_prompt(
            q=q,
            fact_pattern=QUESTIONS[q]["fact_pattern"],
            df_rows=SUPERSETS[q],
            c1=QUESTIONS[q]["C1"],
            c2=QUESTIONS[q]["C2"],
        )

        try:
            pred = call_llm(SYSTEM_PROMPT, user_prompt, model_name)
            validate_pred(pred)

            (OUTDIR / f"pred_{safe_model_name}_{q}.json").write_text(json.dumps(pred, indent=2), encoding="utf-8")
            all_metrics.append(eval_one(q, pred, GROUND_TRUTH, model_name))
            
            elapsed = time.time() - start_time
            print(f"Done ✓ ({elapsed:.2f}s)")
            
        except Exception as e:
            print(f"Failed ✗ (Error: {str(e)})")

if all_metrics:
    metrics = pd.concat(all_metrics, ignore_index=True)
    metrics.to_csv(OUTDIR / "metrics.csv", index=False)
    print("\nSaved outputs to:", OUTDIR)
    display(metrics)
else:
    print("\nNo metrics were generated due to errors.")

[1/5] Testing model: anthropic/claude-opus-4.6
--------------------------------------------------
  -> Processing Q2 (1/1)... Done ✓ (430.03s)

[2/5] Testing model: google/gemini-3.1-pro-preview
--------------------------------------------------
  -> Processing Q2 (1/1)... Done ✓ (64.97s)

[3/5] Testing model: google/gemini-2.5-pro
--------------------------------------------------
  -> Processing Q2 (1/1)... Done ✓ (65.84s)

[4/5] Testing model: openai/gpt-5.4
--------------------------------------------------
  -> Processing Q2 (1/1)... Done ✓ (114.76s)

[5/5] Testing model: moonshotai/kimi-k2.5
--------------------------------------------------
  -> Processing Q2 (1/1)... Done ✓ (1170.17s)

Saved outputs to: irac_outputs/updated_cot

,model,question_number,conclusion,metric,precision,recall,f1,gold_size,pred_size
0,anthropic/claude-opus-4.6,Q2,C1,rules_selected,1.000000,0.636364,0.777778,11,7
1,anthropic/claude-opus-4.6,Q2,C1,edges_support,0.777778,0.437500,0.560000,16,9
2,anthropic/claude-opus-4.6,Q2,C2,rules_selected,1.000000,0.636364,0.777778,11,7
3,anthropic/claude-opus-4.6,Q2,C2,edges_support,0.777778,0.636364,0.700000,11,9
4,google/gemini-3.1-pro-preview,Q2,C1,rules_selected,1.000000,0.272727,0.428571,11,3
5,google/gemini-3.1-pro-preview,Q2,C1,edges_support,0.800000,0.250000,0.380952,16,5
6,google/gemini-3.1-pro-preview,Q2,C2,rules_selected,1.000000,0.363636,0.533333,11,4
7,google/gemini-3.1-pro-preview,Q2,C2,edges_support,0.833333,0.454545,0.588235,11,6
8,google/gemini-2.5-pro,Q2,C1,rules_selected,1.000000,0.363636,0.533333,11,4
9,google/gemini-2.5-pro,Q2,C1,edges_support,0.571429,0.250000,0.347826,16,7
10,google/gemini-2.5-pro,Q2,C2,rules_selected,1.000000,0.363636,0.533333,11,4
11,google/gemini-2.5-pro,Q2,C2,edges_support,0.500000,0.272727,0.352941,11,6
12,openai/gpt-5.4,Q2,C1,rules_selected,1.000000,0.454545,0.625000,11,5
13,openai/gpt-5.4,Q2,C1,edges_support,0.625000,0.312500,0.416667,16,8
14,openai/gpt-5.4,Q2,C2,rules_selected,1.000000,0.545455,0.705882,11,6
15,openai/gpt-5.4,Q2,C2,edges_support,0.666667,0.545455,0.600000,11,9
16,moonshotai/kimi-k2.5,Q2,C1,rules_selected,1.000000,0.727273,0.842105,11,8
17,moonshotai/kimi-k2.5,Q2,C1,edges_support,0.600000,0.562500,0.580645,16,15
18,moonshotai/kimi-k2.5,Q2,C2,rules_selected,1.000000,0.727273,0.842105,11,8
19,moonshotai/kimi-k2.5,Q2,C2,edges_support,0.466667,0.636364,0.538462,11,15

In [9]:
# ============================================================
# 8) Convert JSON files to raw CSV
# ============================================================
import json
import pandas as pd
from pathlib import Path

data = []
input_dir = Path("irac_outputs/updated_cot/")

# Check if directory exists
if input_dir.exists():
    # Iterate through all JSON files in the directory
    for fp in input_dir.glob("pred_*.json"):
        try:
            content = json.loads(fp.read_text(encoding="utf-8"))
            q_num = content.get("question_number", fp.stem.split("_")[-1])
            
            # Reconstruct original Model Name (Strip 'pred_' and '_QX')
            model_name = fp.stem.replace("pred_", "").replace(f"_{q_num}", "")
            if model_name.endswith("_"): 
                model_name = model_name[:-1]
            
            # Extract both C1 and C2 branches
            for concl in ["C1", "C2"]:
                key = f"irac_{concl}"
                if key in content:
                    irac_data = content[key]
                    
                    row = {
                        "Model": model_name,
                        "Question": q_num,
                        "Conclusion_Type": concl,
                        "Issue": irac_data.get("issue", ""),
                        "Rules_Selected_IDs": " | ".join([r.get("id", "") for r in irac_data.get("rules_selected", [])]),
                        "Analysis": irac_data.get("analysis", ""),
                        "Conclusion": irac_data.get("conclusion", ""),
                        "Edges_Support": " | ".join(irac_data.get("edges_support", []))
                    }
                    data.append(row)
        except Exception as e:
            print(f"Error reading {fp.name}: {e}")

    # Compile table and save
    if data:
        df_flattened = pd.DataFrame(data)
        out_path = input_dir / "aggregated_raw_responses.csv"
        df_flattened.to_csv(out_path, index=False)
        print(f"✅ Flattened {len(df_flattened)} conclusion responses into: {out_path}")
        display(df_flattened)
    else:
        print("No valid JSON prediction data found to flatten.")
else:
     print(f"Directory '{input_dir}' not found.")

✅ Flattened 50 conclusion responses into: irac_outputs/updated_cot/aggregated_raw_responses.csv

,Model,Question,Conclusion_Type,Issue,Rules_Selected_IDs,Analysis,Conclusion,Edges_Support
0,google_gemini-3.1-pro-preview,Q5,C1,Whether the States involved in the collection ...,BBNJ_M034 | BBNJ_M035 | BBNJ_M045 | BBNJ_M037 ...,The fact pattern involves the collection of ma...,This supports C1.,BBNJ_M034|C1 | BBNJ_M035|C1 | BBNJ_M045|C1 | B...
1,google_gemini-3.1-pro-preview,Q5,C2,Whether the BBNJ Agreement imposes direct lega...,BBNJ_M021 | BBNJ_M037 | BBNJ_M045,The fact pattern involves a regional oceanogra...,This supports C2.,BBNJ_M021|C2 | BBNJ_M037|C2 | BBNJ_M045|C2
2,google_gemini-2.5-pro,Q5,C1,Whether Indonesia and South Africa have bindin...,BBNJ_M043 | BBNJ_M047 | BBNJ_M021 | BBNJ_M037 ...,The facts establish a clear chain of events in...,This supports C1.,BBNJ_M043|C1 | BBNJ_M047|C1 | BBNJ_M021|C1 | B...
3,google_gemini-2.5-pro,Q5,C2,Whether a violation of the BBNJ Agreement occu...,BBNJ_M021 | BBNJ_M045 | BBNJ_M037 | BBNJ_M043 ...,The BBNJ Agreement imposes obligations on Stat...,This supports C2.,BBNJ_M021|C2 | BBNJ_M045|C2 | BBNJ_M037|C2 | B...
4,openai_gpt-5.4,Q4,C1,"Whether, on these facts and under the cited tr...",CBD_M044 | CBD_M047 | CBD_M046 | CBD_M049 | NA...,The CBD rows first connect the India-EEZ sampl...,This supports C1.,CBD_M044|C1 | CBD_M047|C1 | CBD_M046|C1 | CBD_...
5,openai_gpt-5.4,Q4,C2,"Whether, on these facts and under the cited tr...",CBD_M044 | CBD_M047 | CBD_M046 | CBD_M049 | NA...,The CBD provisions selected are access-oriente...,This supports C2.,CBD_M044|C2 | CBD_M047|C2 | CBD_M046|C2 | CBD_...
6,google_gemini-3.1-pro-preview,Q4,C1,Whether benefit-sharing obligations under the ...,CBD_M049 | NAGOYA_M003 | NAGOYA_M006 | NAGOYA_...,"Under CBD_M049, Contracting Parties have a dut...",This supports C1.,CBD_M049|C1 | NAGOYA_M003|C1 | NAGOYA_M006|C1 ...
7,google_gemini-3.1-pro-preview,Q4,C2,"Whether the open publication of DSI, the absen...",CBD_M044 | CBD_M046 | NAGOYA_M004 | NAGOYA_M00...,"Under CBD_M044, the authority to determine acc...",This supports C2.,CBD_M044|C2 | CBD_M046|C2 | NAGOYA_M004|C2 | N...
8,moonshotai_kimi-k2.5,Q3,C1,Whether benefit-sharing obligations under the ...,NAGOYA_M003 | NAGOYA_M006 | NAGOYA_M015 | NAGO...,The Nagoya Protocol imposes ongoing obligation...,This supports C1.,NAGOYA_M003|C1 | NAGOYA_M006|C1 | NAGOYA_M015|...
9,moonshotai_kimi-k2.5,Q3,C2,Whether benefit-sharing obligations under the ...,NAGOYA_M003 | NAGOYA_M006 | NAGOYA_M015 | NAGO...,The Nagoya Protocol does not automatically ext...,This supports C2.,NAGOYA_M003|C2 | NAGOYA_M006|C2 | NAGOYA_M015|...
10,anthropic_claude-opus-4.6,Q3,C1,Whether the Nagoya Protocol's benefit-sharing ...,NAGOYA_M003 | NAGOYA_M006 | NAGOYA_M019 | NAGO...,NAGOYA_M003 establishes that benefits arising ...,This supports C1.,NAGOYA_M003|C1 | NAGOYA_M006|C1 | NAGOYA_M019|...
11,anthropic_claude-opus-4.6,Q3,C2,Whether benefit-sharing obligations under the ...,NAGOYA_M003 | NAGOYA_M006 | NAGOYA_M013 | NAGO...,NAGOYA_M003 states that benefits shall be shar...,This supports C2.,NAGOYA_M003|C2 | NAGOYA_M006|C2 | NAGOYA_M013|...
12,google_gemini-2.5-pro,Q3,C1,The issue is whether the Nagoya Protocol impos...,NAGOYA_M003 | NAGOYA_M006 | NAGOYA_M019 | NAGO...,The argument for extending benefit-sharing obl...,This supports C1.,NAGOYA_M003|C1 | NAGOYA_M006|C1 | NAGOYA_M019|...
13,google_gemini-2.5-pro,Q3,C2,The issue is whether benefit-sharing obligatio...,NAGOYA_M003 | NAGOYA_M006 | NAGOYA_M013 | NAGO...,The argument that benefit-sharing obligations ...,This supports C2.,NAGOYA_M003|C2 | NAGOYA_M006|C2 | NAGOYA_M013|...
14,anthropic_claude-opus-4.6,Q4,C1,Whether benefit-sharing obligations arise unde...,CBD_M049 | NAGOYA_M003 | NAGOYA_M006 | NAGOYA_...,CBD_M049 establishes that each Contracting Par...,This supports C1.,CBD_M049|C1 | NAGOYA_M003|C1 | NAGOYA_M006|C1 ...
15,anthropic_claude-opus-4.6,Q4,C2,"Whether the open publication of DSI, the absen...",CBD_M047 | CBD_M046 | NAGOYA_M013 | NAGOYA_M01...,The CBD framework conditions access obligation...,This supports C2.,CBD_M047|C2 | CBD_M046|C2 | NAGOYA_M013|C2 | N...
16,anthropic_claude-opus-4.6,Q1,C1,Whether the BBNJ Agreement imposes benefit-sha...,BBNJ_M043 | BBNJ_M047 | BBNJ_M044 | BBNJ_M045 ...,BBNJ_M043 establishes the overarching duty tha...,This supports C1.,BBNJ_M043|C1 | BBNJ_M047|C1 | BBNJ_M044|C1 | B...
17,anthropic_claude-opus-4.6,Q1,C2,"Whether, on these facts, the BBNJ Agreement's ...",BBNJ_M043 | BBNJ_M049 | BBNJ_M044 | BBNJ_M046 ...,The threshold question is whether BBNJ_M043's ...,This supports C2.,BBNJ_M043|C2 | BBNJ_M049|C2 | BBNJ_M044|C2 | B...
18,google_gemini-3.1-pro-preview,Q2,C1,"Whether Argentina, as a Contracting Party, has...",CBD_M019 | NAGOYA_M016 | NAGOYA_M006,The fact pattern involves a researcher accessi...,This supports C1.,CBD_M019|C1 | NAGOYA_M016|C1 | NAGOYA_M006|C1 ...
19,google_gemini-3.1-pro-preview,Q2,C2,Whether Argentina's issuance of an access perm...,CBD_M019 | NAGOYA_M008 | NAGOYA_M014 | NAGOYA_...,The fact pattern describes a scenario where Ar...,This supports C2.,CBD_M019|C2 | NAGOYA_M008|C2 | NAGOYA_M014|C2 ...
20,moonshotai_kimi-k2.5,Q4,C1,Whether benefit-sharing obligations arise unde...,CBD_M049 | NAGOYA_M003 | NAGOYA_M006 | NAGOYA_...,"Under CBD_M049, Contracting Parties bear a dut...",This supports C1.,CBD_M049|C1 | NAGOYA_M003|C1 | NAGOYA_M006|C1 ...
21,moonshotai_kimi-k2.5,Q4,C2,"Whether the lack of formal access agreements, ...",CBD_M044 | CBD_M047 | CBD_M046 | NAGOYA_M008 |...,"Under CBD_M044, India retains sovereign rights...",This supports C2.,CBD_M044|C2 | CBD_M047|C2 | CBD_M046|C2 | NAGO...
22,openai_gpt-5.4,Q2,C1,Whether the provided treaty rows support the c...,NAGOYA_M016 | CBD_M019 | NAGOYA_M006 | NAGOYA_...,NAGOYA_M016 is the most direct rule for these ...,This supports C1.,NAGOYA_M016|C1 | CBD_M019|C1 | NAGOYA_M006|C1 ...
23,openai_gpt-5.4,Q2,C2,Whether the provided treaty rows support the c...,NAGOYA_M008 | NAGOYA_M016 | NAGOYA_M014 | NAGO...,NAGOYA_M008 supports C2 because its Hohfeldian...,This supports C2.,NAGOYA_M008|C2 | NAGOYA_M016|C2 | NAGOYA_M014|...
24,anthropic_claude-opus-4.6,Q5,C1,"Whether Indonesia and South Africa, as States ...",BBNJ_M021 | BBNJ_M034 | BBNJ_M035 | BBNJ_M037 ...,"The BBNJ Agreement places comprehensive, overl...",This supports C1.,BBNJ_M021|C1 | BBNJ_M034|C1 | BBNJ_M035|C1 | B...
25,anthropic_claude-opus-4.6,Q5,C2,"Whether, under the BBNJ Agreement, private ent...",BBNJ_M021 | BBNJ_M037 | BBNJ_M045 | BBNJ_M043 ...,The BBNJ Agreement consistently addresses its ...,This supports C2.,BBNJ_M021|C2 | BBNJ_M037|C2 | BBNJ_M045|C2 | B...
26,google_gemini-2.5-pro,Q2,C1,"Whether Argentina, as a Party to the CBD and N...",CBD_M019 | NAGOYA_M016 | NAGOYA_M006 | NAGOYA_...,Argentina’s issuance of a permit without commu...,This supports C1.,CBD_M019|C1 | NAGOYA_M016|C1 | NAGOYA_M006|C1 ...
27,google_gemini-2.5-pro,Q2,C2,Whether Argentina's grant of a permit for acce...,NAGOYA_M008 | NAGOYA_M004 | CBD_M019 | NAGOYA_...,Argentina acted within its sovereign rights an...,This supports C2.,NAGOYA_M008|C2 | NAGOYA_M004|C2 | CBD_M019|C2 ...
28,anthropic_claude-opus-4.6,Q2,C1,Whether access to marine genetic resources and...,NAGOYA_M016 | CBD_M019 | NAGOYA_M008 | NAGOYA_...,"The facts establish that TK is ""associated wit...",This supports C1.,NAGOYA_M016|C1 | CBD_M019|C1 | NAGOYA_M008|C1 ...
29,anthropic_claude-opus-4.6,Q2,C2,Whether the domestic-law qualifiers in the Nag...,NAGOYA_M016 | NAGOYA_M008 | NAGOYA_M014 | NAGO...,The central textual feature supporting C2 is t...,This supports C2.,NAGOYA_M016|C2 | NAGOYA_M008|C2 | NAGOYA_M014|...
30,moonshotai_kimi-k2.5,Q1,C1,"Whether Australia, as a Contracting Party, bea...",BBNJ_M043 | BBNJ_M047 | BBNJ_M044 | BBNJ_M045 ...,"Under BBNJ_M043, Contracting Parties hold a Ho...",This supports C1.,BBNJ_M043|C1 | BBNJ_M047|C1 | BBNJ_M044|C1 | B...
31,moonshotai_kimi-k2.5,Q1,C2,Whether benefit-sharing obligations apply to t...,BBNJ_M043 | BBNJ_M047 | BBNJ_M049 | BBNJ_M044 ...,While BBNJ_M043 states that benefits shall be ...,This supports C2.,BBNJ_M043|C2 | BBNJ_M047|C2 | BBNJ_M049|C2 | B...
32,openai_gpt-5.4,Q3,C1,Whether C1 is supported on these facts under t...,NAGOYA_M003 | NAGOYA_M006 | NAGOYA_M019 | NAGO...,NAGOYA_M003 gives each Contracting Party a dut...,This supports C1.,NAGOYA_M003|C1 | NAGOYA_M006|C1 | NAGOYA_M019|...
33,openai_gpt-5.4,Q3,C2,Whether C2 is supported on these facts under t...,NAGOYA_M013 | NAGOYA_M003 | NAGOYA_M006 | NAGO...,NAGOYA_M013 places on each Contracting Party a...,This supports C2.,NAGOYA_M013|C2 | NAGOYA_M003|C2 | NAGOYA_M006|...
34,openai_gpt-5.4,Q1,C1,"Whether, on these facts and under the provided...",BBNJ_M043 | BBNJ_M044 | BBNJ_M047 | BBNJ_M045,The central obligation comes from BBNJ_M043. I...,This supports C1.,BBNJ_M043|C1 | BBNJ_M044|C1 | BBNJ_M047|C1 | B...
35,openai_gpt-5.4,Q1,C2,"Whether, on these facts and under the provided...",BBNJ_M043 | BBNJ_M044 | BBNJ_M047 | BBNJ_M049,The best argument for C2 begins with the struc...,This supports C2.,BBNJ_M043|C2 | BBNJ_M044|C2 | BBNJ_M047|C2 | B...
36,openai_gpt-5.4,Q5,C1,Whether C1 is supported on these facts under t...,BBNJ_M021 | BBNJ_M034 | BBNJ_M035 | BBNJ_M037 ...,The facts fit the selected provisions because ...,This supports C1.,BBNJ_M021|C1 | BBNJ_M034|C1 | BBNJ_M035|C1 | B...
37,openai_gpt-5.4,Q5,C2,Whether C2 is supported on these facts under t...,BBNJ_M021 | BBNJ_M034 | BBNJ_M035 | BBNJ_M037 ...,The selected treaty text supports C2 because e...,This supports C2.,BBNJ_M021|C2 | BBNJ_M034|C2 | BBNJ_M035|C2 | B...
38,google_gemini-2.5-pro,Q1,C1,The issue is whether Australia has a duty to e...,BBNJ_M043 | BBNJ_M047 | BBNJ_M044 | BBNJ_M045 ...,Benefit-sharing obligations apply to the Austr...,This supports C1.,BBNJ_M043|C1 | BBNJ_M047|C1 | BBNJ_M044|C1 | B...
39,google_gemini-2.5-pro,Q1,C2,The issue is whether any enforceable benefit-s...,BBNJ_M043 | BBNJ_M047 | BBNJ_M049 | BBNJ_M044 ...,No enforceable benefit-sharing obligations app...,This supports C2.,BBNJ_M043|C2 | BBNJ_M047|C2 | BBNJ_M049|C2 | B...
40,google_gemini-2.5-pro,Q4,C1,The issue is whether benefit-sharing obligatio...,NAGOYA_M003 | NAGOYA_M006 | NAGOYA_M045 | NAGO...,Benefit-sharing obligations arise from the com...,This supports C1.,NAGOYA_M003|C1 | NAGOYA_M006|C1 | NAGOYA_M045|...
41,google_gemini-2.5-pro,Q4,C2,The issue is whether benefit-sharing obligatio...,NAGOYA_M045 | NAGOYA_M048 | NAGOYA_M003 | CBD_...,Benefit-sharing obligations do not arise for t...,This supports C2.,NAGOYA_M045|C2 | NAGOYA_M048|C2 | NAGOYA_M003|...
42,moonshotai_kimi-k2.5,Q5,C1,Whether Indonesia and South Africa have obliga...,BBNJ_M021 | BBNJ_M034 | BBNJ_M035 | BBNJ_M045 ...,"Under BBNJ_M021, Indonesia and South Africa, a...",This supports C1.,BBNJ_M021|C1 | BBNJ_M034|C1 | BBNJ_M035|C1 | B...
43,moonshotai_kimi-k2.5,Q5,C2,Whether the BBNJ Agreement imposes direct lega...,BBNJ_M021 | BBNJ_M034 | BBNJ_M035 | BBNJ_M037 ...,The BBNJ Agreement establishes obligations exc...,This supports C2.,BBNJ_M021|C2 | BBNJ_M034|C2 | BBNJ_M035|C2 | B...
44,google_gemini-3.1-pro-preview,Q1,C1,"Whether Australia, as a Contracting Party, bea...",BBNJ_M043 | BBNJ_M047 | BBNJ_M044,"Under BBNJ_M043, Contracting Parties have a br...",This supports C1.,BBNJ_M043|C1 | BBNJ_M047|C1 | BBNJ_M044|C1 | B...
45,google_gemini-3.1-pro-preview,Q1,C2,Whether Australia is exempt from enforcing fur...,BBNJ_M045 | BBNJ_M044 | BBNJ_M049,The fact pattern indicates that the Australian...,This supports C2.,BBNJ_M045|C2 | BBNJ_M044|C2 | BBNJ_M049|C2 | B...
46,moonshotai_kimi-k2.5,Q2,C1,Whether Argentina’s issuance of an access perm...,NAGOYA_M016 | NAGOYA_M008 | CBD_M019 | NAGOYA_...,"Under NAGOYA_M016, Argentina as Contracting Pa...",This supports C1.,NAGOYA_M016|C1 | NAGOYA_M008|C1 | CBD_M019|C1 ...
47,moonshotai_kimi-k2.5,Q2,C2,Whether Argentina’s permit is legally adequate...,NAGOYA_M016 | NAGOYA_M008 | NAGOYA_M014 | NAGO...,NAGOYA_M016 provides that each Party shall tak...,This supports C2.,NAGOYA_M016|C2 | NAGOYA_M008|C2 | NAGOYA_M014|...
48,google_gemini-3.1-pro-preview,Q3,C1,Whether the Nagoya Protocol imposes ongoing ob...,NAGOYA_M003 | NAGOYA_M006 | NAGOYA_M019 | NAGO...,"Under NAGOYA_M003, Contracting Parties have a ...",This supports C1.,NAGOYA_M003|C1 | NAGOYA_M006|C1 | NAGOYA_M048|...
49,google_gemini-3.1-pro-preview,Q3,C2,Whether benefit-sharing obligations automatica...,NAGOYA_M003 | NAGOYA_M015 | NAGOYA_M019,"Under NAGOYA_M003, the duty of Contracting Par...",This supports C2.,NAGOYA_M003|C2 | NAGOYA_M019|C2 | NAGOYA_M015|...

In [10]:
# ============================================================
# 9) Visualise Metrics: With vs Without Reasoning
# ============================================================
import pandas as pd
import plotly.express as px
from pathlib import Path

# Set paths to the CSV files
# path_without = Path("irac_outputs/without_reasoning/metrics_without_reasoning.csv")
path_with = Path("irac_outputs/updated_cot/metrics.csv")

dfs = []

# # Load "Without Reasoning" metrics
# if path_without.exists():
#     df_no = pd.read_csv(path_without)
#     df_no["Reasoning"] = "Without Reasoning"
#     dfs.append(df_no)
# else:
#     print(f"File not found: {path_without}")

# Load "With Reasoning" metrics
if path_with.exists():
    df_yes = pd.read_csv(path_with)
    df_yes["Reasoning"] = "With Reasoning"
    dfs.append(df_yes)
else:
    print(f"File not found: {path_with}")

# Combine datasets
if dfs:
    df_all = pd.concat(dfs, ignore_index=True)
    
    # We'll calculate the mean F1 score grouped by model, metric, and reasoning type
    df_grouped = df_all.groupby(["model", "metric", "Reasoning"])["f1"].mean().reset_index()

    # Visualise the Results (F1 Score)
    fig = px.bar(
        df_grouped,
        x="model",
        y="f1",
        color="Reasoning",
        barmode="group",
        facet_col="metric", 
        title="Model Performance (F1 Score): Chain of Thought",
        labels={"f1": "Average F1 Score", "model": "Model Name"},
        template="plotly_white"
    )
    
    fig.update_layout(xaxis_tickangle=-45, height=600, width=1200)
    
    # Render in Jupyter with fallback options
    try:
        fig.show()
    except Exception as e:
        print(f"Note: {e}")
        print("Rendering as HTML file instead...")
        fig.write_html(Path("irac_outputs/model_comparison_chart.html"))
        print("✅ Chart saved to: irac_outputs/model_comparison_chart.html")

else:
    print("Could not load any data to visualize.")

In [12]:
# Load the current metrics
import pandas as pd
# df = pd.read_csv("irac_outputs/updated_cot/metrics.csv")
df = pd.read_csv("metrics_all_LLMs.csv")
# Compute macro f1 per model (average of f1)
macro_f1 = df.groupby("model")["f1"].mean().reset_index()
print("Macro F1 Scores by Model:")
display(macro_f1.sort_values(by="f1", ascending=False))

# Identify best model
best_model = macro_f1.loc[macro_f1['f1'].idxmax(), 'model']
print(f"\nBest Model: {best_model}")

# Get table for best model by question (including precision, recall, f1, and ground/pred sizes)
best_model_df = df[df["model"] == best_model]
print(f"\n{best_model} Breakdown by Question (Averages):")
q_breakdown = best_model_df.groupby("question_number")[["precision", "recall", "f1"]].mean().reset_index()
display(q_breakdown)

# Alternate: table based on each question per model
print("\nAverage F1 by Model and Question:")
model_q_f1 = df.groupby(["model", "question_number"])["f1"].mean().unstack()
display(model_q_f1)

Macro F1 Scores by Model:

                           model        f1
3           moonshotai/kimi-k2.5  0.617414
4                 openai/gpt-5.4  0.559993
0      anthropic/claude-opus-4.6  0.551992
1          google/gemini-2.5-pro  0.484988
2  google/gemini-3.1-pro-preview  0.408069

Best Model: moonshotai/kimi-k2.5

moonshotai/kimi-k2.5 Breakdown by Question (Averages):

  question_number  precision    recall        f1
0              Q1   0.713889  0.733333  0.712698
1              Q2   0.766667  0.663352  0.700829
2              Q3   0.792411  0.655370  0.704581
3              Q4   0.567651  0.356291  0.426740
4              Q5   0.714286  0.446429  0.542222

Average F1 by Model and Question:

question_number,Q1,Q2,Q3,Q4,Q5
model,,,,,
anthropic/claude-opus-4.6,0.624236,0.703889,0.623377,0.383333,0.425123
google/gemini-2.5-pro,0.663045,0.441858,0.585165,0.372646,0.362224
google/gemini-3.1-pro-preview,0.502778,0.482773,0.412406,0.348598,0.293791
moonshotai/kimi-k2.5,0.712698,0.700829,0.704581,0.426740,0.542222
openai/gpt-5.4,0.609314,0.586887,0.597015,0.531748,0.475000